# Generated by Django 4.2 on 2023-04-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_date'),
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_order', to='order.order'),
        ),
    ]
