# Generated by Django 4.2 on 2023-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_courier_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
