# Generated by Django 4.2 on 2023-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Astana', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(default='Kazakhstan', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default='Kabanbay Batyr', max_length=50),
        ),
    ]
