# Generated by Django 4.2 on 2023-04-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_city_alter_order_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aIIN',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
